version: '3.3'
services:
    coredns:
        build:
          context: ./dns
        container_name: asor-coredns
        restart: always
        expose:
            - '53'
            - '53/udp'
        ports:
            - '53:53'
            - '53:53/udp'
        volumes:
            - './dns:/etc/coredns'
        networks:
            - custom_network
    postfix:
        image: cisagov/postfix
        init: true
        restart: always
        environment:
            - PRIMARY_DOMAIN=postfixasor.com
        expose:
            - '25'
            - '25/tcp'
            - '587'
            - '587/tcp'
            - '993'
            - '993/tcp'
        ports:
            - '25:25'
            - '25:25/tcp'
            - '587:587'
            - '587:587/tcp'
            - '993:993'
            - '993:993/tcp'
        networks:
            - custom_network
    
networks:
  custom_network:
    driver: bridge