version: '3.3'
services:
    coredns:
        build:
          context: ./dns
        container_name: asor-coredns
        restart: always
        expose:
            - '53'
            - '53/udp'
        ports:
            - '53:53'
            - '53:53/udp'
        volumes:
            - './dns:/etc/coredns'
        networks:
            - custom_network

    postfix:
        build:
          context: ./postfix-edinson
        container_name: postfix-email
        restart: always
        expose:
            - '25' 
            - '143'
            - '110'
            - '80'
        ports:
            - '25:25' 
            - '143:143'
            - '110:110'
            - '80:80'
    
networks:
  custom_network:
    driver: bridge