version: '3.3'
services:
    coredns:
        build:
          context: ./dns
        container_name: asor-coredns
        restart: always
        expose:
            - '53'
            - '53/udp'
        ports:
            - '53:53'
            - '53:53/udp'
        volumes:
            - './dns:/etc/coredns'
        networks:
            - custom_network
    postfix:
        image: cisagov/postfix
        init: true
        restart: always
        environment:
            - PRIMARY_DOMAIN=postfixasor.com
        ports:
            - target: "25"
              published: "1025"
              protocol: tcp
              mode: host
            - target: "587"
              published: "1587"
              protocol: tcp
              mode: host
            - target: "993"
              published: "1993"
              protocol: tcp
              mode: host
        networks:
            - custom_network
    
networks:
  custom_network:
    driver: bridge