version: '3.3'
services:
    coredns:
        build:
          context: ./dns
        container_name: asor-coredns
        restart: always
        expose:
            - '53'
            - '53/udp'
        ports:
            - '53:53'
            - '53:53/udp'
        volumes:
            - './dns:/etc/coredns'
        networks:
            - custom_network
    postfix:
        image: daone/postfix-dovecot
        container_name: asor-postfix
        restart: always
        environment:
        - maildomain=postfixasor.com
        expose:
            - '25'
            - '143'
            - '465'
            - '993'
        ports:
            - '25:25'
            - '143:143'
            - '465:465'
            - '993:993'
        networks:
            - custom_network

networks:
  custom_network:
    driver: bridge