version: '3.3'
services:
    coredns:
        build:
          context: ./dns
        container_name: asor-coredns
        restart: always
        expose:
            - '53'
            - '53/udp'
        ports:
            - '53:53'
            - '53:53/udp'
        volumes:
            - './dns:/etc/coredns'
        networks:
            - custom_network
    postfix:
        build:
          context: ./postfix
        container_name: asor-postfix
        restart: always
        hostname: postfixasor.com
        expose:
            - '25'
            - '80'
            - '110'
            - '143'
            - '995'
        ports:
            - '25:25'
            - '80:80'
            - '110:110'
            - '143:143'
            - '995:995'
        networks:
            - custom_network
    # adminer:
    #     image: adminer
    #     container_name: asor-adminer
    #     restart: always
    #     ports:
    #         - '8080:8080'
    #     networks:
    #         - custom_network
    # dbmysql:
    #     image: mysql:5.7
    #     container_name: asor-db
    #     # volumes:
    #     #     - ./db/mysql:/var/lib/mysql
    #     ports:
    #         - '3306:3306'
    #     environment:
    #         - MYSQL_DATABASE=roundcube
    #         - MYSQL_ROOT_PASSWORD=root
    #         # - MYSQL_ROOT_PASSWORD=roundcube2023
    #         # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    #         # - MYSQL_ROOT_HOST="%"
    #         # - MYSQL_DATABASE=roundcube
    #         # - MYSQL_USER=user1
    #         # - MYSQL_PASSWORD=passuser1
    #     networks:
    #         - custom_network
    # roundcubemail:
    #     image: roundcube/roundcubemail:latest
    #     container_name: roundcubemail
    #     hostname: mail.postfixasor.com
    #     depends_on:
    #         - roundcubedb
    #     links:
    #         - roundcubedb
    #     volumes:
    #         - ./www:/var/www/html
    #         - ./roundcube:/var/roundcube/config/
    #     ports:
    #         - '9001:80'
    #     environment:
    #         - ROUNDCUBEMAIL_DB_TYPE=mysql
    #         - ROUNDCUBEMAIL_DB_HOST=roundcubedb
    #         - ROUNDCUBEMAIL_DB_PASSWORD=roundcube-mysql-pw
    #         - ROUNDCUBEMAIL_SKIN=elastic
    #         - ROUNDCUBEMAIL_DEFAULT_HOST=mail.postfixasor.com
    #         - ROUNDCUBEMAIL_SMTP_SERVER=smtp.postfixasor.com
    #         - ROUNDCUBEMAIL_SMTP_PORT=25
    #     networks:
    #         - custom_network

networks:
  custom_network:
    driver: bridge
    name: custom_network
    ipam: 
      config:
        - subnet: 172.19.0.0/24