version: '3.3'
services:
    coredns:
        build:
          context: ./dns
        container_name: asor-coredns
        restart: always
        expose:
            - '53'
            - '53/udp'
        ports:
            - '53:53'
            - '53:53/udp'
        volumes:
            - './dns:/etc/coredns'
        networks:
            - custom_network
    postfix:
        container_name: 'asor-postfix'
        image: 'humpedli/docker-postfix-dovecot'
        ports:
            - '25:25'
            - '587:587'
            - '993:993'
        volumes:
            - '/etc/vmail-postfix:/home/vmail'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - HOSTNAME=postfixasor.com
            - CUSTOM_NETWORKS=192.168.0.0/16
            - POSTMASTER=omarrm@postfixasor.com
            - MYSQL_HOST=mysql
            - MYSQL_PORT=3306
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=postfix
        depends_on:
            - mysql
        restart: 'always'
    mysql:
        image: mysql:5.7
        container_name: 'asor-postfix'
        restart: always
        environment:
            - MYSQL_DATABASE=postfix
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - my-db:/var/lib/mysql
        networks:
            - custom_network
    # postfix:
    #     image: daone/postfix-dovecot
    #     container_name: asor-postfix
    #     restart: always
    #     environment:
    #     - maildomain=postfixasor.com
    #     expose:
    #         - '25'
    #         - '143'
    #         - '465'
    #         - '993'
    #     ports:
    #         - '25:25'
    #         - '143:143'
    #         - '465:465'
    #         - '993:993'
    #     networks:
    #         - custom_network

volumes:
  my-db:
networks:
  custom_network:
    driver: bridge